dist: xenial

sudo: required

language: python

python:
  - 3.8

install: pip install -r requirements/dev.txt

services:
  - docker

before_install:
  - docker pull localstack/localstack
  - docker run --rm -d -p 4566:4566 localstack/localstack

script: py.test tests --cov=src

after_success:
  - coveralls
