dist: xenial

sudo: required

language: python

python:
  - 3.8

services:
  - docker

before_install:
  - docker pull localstack/localstack
  - docker run --rm -d -p 4566:4566 localstack/localstack

install: pip install -r requirements/dev.txt

env:
  global:
    - REGION_NAME=eu-west-1
    - DYNAMODB_ENDPOINT_URL=http://localstack:4566
    - COMMENTS_TABLE=comments-table

script: py.test tests --cov=src

after_success:
  - coveralls
