version: "3"
services:

  comments-engine:
    container_name: "comments-engine"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REGION_NAME=eu-west-1
      - DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - COMMENTS_TABLE=comments-table
    volumes:
      - ".:/code/"
    ports:
      - "5000:5000"
    command: flask run

  serverless:
    container_name: "serverless"
    build:
      context: .
      dockerfile: ServerlessDockerfile
    env_file:
      - .env
    volumes:
      - ".:/code/"

  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LOCALSTACK_HOSTNAME=localstack
