version: "3"
services:

  comments-engine:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ".:/code/"
    ports:
      - "5000:5000"
    command: flask run

  serverless:
    build:
      context: .
      dockerfile: ServerlessDockerfile
    env_file:
      - .env
    volumes:
      - ".:/code/"
